<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\freetypesharpv\FreeTypeSharp\FreeTypeSharp.csproj" />
    <ProjectReference Include="..\FontStashSharp.Base\FontStashSharp.Base.csproj" />
  </ItemGroup>
</Project>
